### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by TLMNicolas** [bassclarinetl2/power_eagle#1]
How is this component to be used in HA?
Tried in custom_components but no luck. Thanks

**Comment by bassclarinetl2** [comment]
It's an abandoned attempt to get information from a rainforest eagle power
meter bridge

**Comment by codewise-nicolas** [comment]
Ah to bad, it looks very promising in terms of what it could do.
I did see your configuration files and use the REST examples to come up with my own, thanks.

**Comment by TLMNicolas** [comment]
Ah to bad, it looks very promising in terms of what it could do.
I did see your configuration files and use the REST examples to come up with my own, thanks.
